### ISSUE TITLE
RangeError: Maximum call stack size exceeded.

### ISSUE THREAD

**Issue by ackwell** [xivanalysis/xivanalysis#18]
https://sentry.io/share/issue/be3e0661c91547d6b8840b81d849d425/

```
RangeError: Maximum call stack size exceeded.
  at splice ([native code])
  at stringify ([native code])
  at None (parser/core/Parser.js:146:11)
  at forEach ([native code])
  at triggerEvent (parser/core/Parser.js:136:24)
...
(45 additional frame(s) were not displayed)
```

This is probably only an issue on some browsers, it certainly loads fine for me. That said, worth looking into.

Initial thoughts would suggest that instead of immediately calling `triggerEvent` in the `fabricateEvent` call, it can be pushed into a temporary array at the parser level, which can be read from during the standard event loop and used up before continuing.

**Comment by ackwell** [comment]
Take it back, got a repro, I'm just an idiot. Infinite loop caused by summoning Bahamut right at the start of the fight, my code to handle that was actually broken and has been for ages :blobsweat:.

Fixed in f85d82c.
